### ISSUE TITLE
Lualine not working

### ISSUE THREAD

**Issue by BenHerbst** [wthollingsworth/pomodoro.nvim#3]

**Comment by imkerberos** [comment]
README is incorrect. Use this
`
require('lualine').setup({
    sections = {
        lualine_c = { 'filename', require('pomodoro').statusline }
    }
})
`

**Comment by BenHerbst** [comment]
Okay thank you

**Comment by wthollingsworth** [comment]
Hey, sorry for the late response Ben!  I haven't actually been using this lately.  Did that end up working for you?  You may also want to try out the fork [here](https://github.com/jvaverka/pomodoro.nvim).  Not sure if it's better watched/maintained.

**Comment by wthollingsworth** [comment]
Closing this since it was correctly documented in a recent PR.
